Translated the new LTS page
vuejs/v2.cn.vuejs.org pull request #1230
Opened 2023-01-19 16:44 UTC by Jinjiang

最终考虑把 extended LTS 翻译成了“延长版 LTS”，比如原文：

```
we have partnered with industry experts to provide Extended LTS for Vue 2
```

翻译成了：

```
我们和业内的专家们合作推出了 Vue 2 的延长版 LTS 服务
```

另外：

- LTS 翻译为了“长期技术支持”
- EOL 翻译为了“生命周期截止”或“生命周期截止日”

2023-01-29 12:39 UTC, Justineo requested changes
生命周期截止日 -> 支持终止日

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +Vue 2.7 是当前，同时也是最后一个 Vue 2.x 的小版本更新。Vue 2.7 会以其发布日期，即 2022 年 7 月 1 日开始计算，提供 18 个月的长期技术支持 (LTS：long-term support)。在此期间，Vue 2 将会提供必要的 bug 修复和安全修复，但不再提供新特性。
```suggestion
Vue 2.7 是当前、同时也是最后一个 Vue 2.x 的次级版本更新。Vue 2.7 会以其发布日期，即 2022 年 7 月 1 日开始计算，提供 18 个月的长期技术支持 (LTS：long-term support)。在此期间，Vue 2 将会提供必要的 bug 修复和安全修复，但不再提供新特性。
```

小版本是不是有点歧义？次级版本你觉得如何？

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +### 留在 Vue 2
```suggestion
### 继续使用 Vue 2
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +有些团队可能鉴于有限的投入、预算、风险承受能力、或不兼容 Vue 3 的依赖，不会升级到 Vue 3。我们完全可以理解这种做法，并将确保留在 Vue 2 是完全可行的选项，即便在其生命周期截止之后。
```suggestion
有些团队可能鉴于有限的投入、预算、风险承受能力、或有不兼容 Vue 3 的依赖，而在此时间段内无法升级到 Vue 3。我们对此完全理解，并将确保继续使用 Vue 2 是完全可行的选项，即便在其生命周期截止之后。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +从技术角度看，Vue 2 是一项稳定且实战考验过的技术。如果它现在可以很好的支持你的工作，我们相信在可预见的未来它会仍然如此。
```suggestion
从技术角度看，Vue 2 是一项稳定且实战考验过的技术。如果它现在可以很好地支持你的工作，我们相信在可预见的未来仍然如此。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +#### 安全和合规的角度
```suggestion
#### 安全与合规
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +有些团队的主要鼓励可能来自于安全、合规和浏览器兼容性方面。
```suggestion
有些团队的主要顾虑可能来自于安全、合规和浏览器兼容性方面。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +- 软件的生命周期截止之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个版本来应对合规或公司政策问题。
```suggestion
- 软件的生命周期截止之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个受支持的版本来应对合规或公司政策问题。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +- 如果你在向客户提供带有 SLA (Service Level Agreement) 协议的应用，你*需要*在技术栈中避免包含生命周期截止日的软件。
```suggestion
- 如果你在向客户提供带有服务级别协议 (SLA：Service Level Agreement) 协议的应用，你*需要*在技术栈中避免包含生命周期截止日的软件。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +- 浏览器有时会发布一些会破坏老旧库的变更。这样的情况技术发生，但理论上难以避免。
```suggestion
- 浏览器有时会发布一些会破坏老旧库的变更。这样的情况极少发生，但理论上难以完全避免。
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +## 带回的特性
移植回来的特性

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +### 和 Vue 3 不同的行为
```suggestion
### 与 Vue 3 的行为差异
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +- 当从外部构建 CJS 版本时，打包工具应该有能力在内部对 ESM 进行转换 (ESM interop)。
```suggestion
- 当调用外置的 CJS 版本进行打包时，打包工具应该有能力处理与 ESM 模块的互操作 (ESM interop)。
```

意思我理解是用了 Vue 的 CJS 版本，但是配了 externals，不知道理解的对不对

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +- `readonly()` **会**创建一个独立的对象，但是其不会追踪新添加的属性，也不会在数组上工作。
```suggestion
- `readonly()` **会**创建一个独立的对象，但是其不会追踪新添加的属性，也不会对数组生效。
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +此外，我们**并没有**带回以下特性：
```suggestion
此外，我们**并没有**移植回以下特性：
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +- ❌ `<script setup>` 中的顶级 `await` (Vue 2 不支持异步组件初始化)
```suggestion
- ❌ `<script setup>` 中的顶层 `await` (Vue 2 不支持异步组件初始化)
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +尽管 Vue 3 是当前的默认主版本，我们非常理解许多由于依赖的兼容性、浏览器的兼容性需求、或精力有限不足以完成升级等因素，仍然留在 Vue 2 的用户。在 Vue 2.7 中，我们从 Vue 3 带回了最重要的一些特性，使得 Vue 2 用户也可以享有这些便利。
```suggestion
尽管 Vue 3 是当前的默认主版本，我们非常理解许多由于依赖的兼容性、浏览器的兼容性需求、或精力有限不足以完成升级等因素，仍然留在 Vue 2 的用户。在 Vue 2.7 中，我们从 Vue 3 移植回了最重要的一些特性，使得 Vue 2 用户也可以享有这些便利。
```

2023-01-29 12:39 UTC, Justineo commented on src/lts/index.md
> +此外，我们也已经把大部分 Vue 3 重要的特性带回了 [Vue 2.7](/v2/guide/migration-vue-2-7.html)，包括组合式 API 和 `<script setup>`。这使得 Vue 2 的项目可以提升其可扩展性、充分利用生态系统中最新的库、以及为潜在的 Vue 3 升级机会做更好的准备。
```suggestion
此外，我们也已经把大部分 Vue 3 重要的特性移植回了 [Vue 2.7](/v2/guide/migration-vue-2-7.html)，包括组合式 API 和 `<script setup>`。这使得 Vue 2 的项目可以提升其可扩展性、充分利用生态系统中最新的库、以及为潜在的 Vue 3 升级机会做更好的准备。
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +4. 如果你曾经使用了 [`@vue/composition-api`](https://github.com/vuejs/composition-api)，将其导入语句切换至 `vue` 即可。注意有些通过插件暴露的 API，例如 `createApp`，并没有被带回 2.7。
```suggestion
4. 如果你曾经使用了 [`@vue/composition-api`](https://github.com/vuejs/composition-api)，将其导入语句切换至 `vue` 即可。注意有些之前通过插件暴露的 API，例如 `createApp`，并没有被移植回 2.7。
```

2023-01-29 12:39 UTC, Justineo commented on src/v2/guide/migration-vue-2-7.md
> +Vue Devtools 6.2.0 已经支持了 2.7 组合式 API 状态的审查，但该扩展可能仍然需要几天时间在各自的发布平台上通过审核。
后面半句原文已经不对了 😅

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +Vue 3 是当前 Vue 的最高主版本。它提供了更好的性能和更好的 TypeScript 支持，并拥有诸如 Teleport、Suspense 和模板中多个根元素等 Vue 2 中没有的新特性。
```suggestion
Vue 3 是当前 Vue 的最高主版本。它提供了更好的性能和更好的 TypeScript 支持，并拥有诸如 Teleport、Suspense 和模板语法可多个根元素等 Vue 2 中没有的新特性。
```
补齐下语义

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +尽管存在不兼容变更，Vue 两个主版本之间主要的 API 依然是共享的。所以团队仍然可以把 Vue 2 的相关知识带到 Vue 3 使用。长期来看，我们也会尽可能避免类似 Vue 2 和 Vue 3 之间的这种不兼容变更。兼容性和生态的稳定性将会是我们未来发布的最高优先考量。而新特性的引入也不会导致大的迁移。
```suggestion
尽管存在不兼容的变更，Vue 两个主版本之间主要的 API 依然是共享的。所以团队仍然可以把 Vue 2 的相关知识带到 Vue 3 使用。长期来看，我们也会尽可能避免类似 Vue 2 和 Vue 3 之间的这种不兼容变更。兼容性和生态的稳定性将会是我们未来发布的最高优先考量。而新特性的引入也不会导致大的迁移。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +- 如果你在向客户提供带有 SLA (Service Level Agreement) 协议的应用，你*需要*在技术栈中避免包含生命周期截止日的软件。
```suggestion
- 如果你在向客户提供带有 SLA (Service Level Agreement) 协议的应用，你*需要*在技术栈中避免使用终止支持的软件。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +- 浏览器有时会发布一些会破坏老旧库的变更。这样的情况技术发生，但理论上难以避免。
```suggestion
- 浏览器有时会发布一些会破坏老旧库的变更。这样的情况极为罕见，但理论上难以避免。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +Vue 2.7 是 Vue 2 最新的次级版本。其提供了内置的[组合式 API](https://cn.vuejs.org/guide/extras/composition-api-faq.html#composition-api-faq) 支持。
```suggestion
Vue 2.7 是 Vue 2 最新的小版本。其提供了内置的[组合式 API](https://cn.vuejs.org/guide/extras/composition-api-faq.html#composition-api-faq) 支持。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +- `readonly()` **会**创建一个独立的对象，但是其不会追踪新添加的属性，也不会在数组上工作。
```suggestion
- `readonly()` **会**创建一个独立的对象，但是其不会追踪新添加的属性，不支持数组。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +   如果没有这样做，你需要移除整个 `node_modules` 和版本锁定文件，然后重新安装，以确保它们都升到了最新版本。
```suggestion
   否则，你需要移除整个 `node_modules` 和版本锁定文件，然后重新安装，以确保它们都升到了最新版本。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +4. 如果你曾经使用了 [`@vue/composition-api`](https://github.com/vuejs/composition-api)，将其导入语句切换至 `vue` 即可。注意有些通过插件暴露的 API，例如 `createApp`，并没有被带回 2.7。
```suggestion
4. 如果你曾经使用了 [`@vue/composition-api`](https://github.com/vuejs/composition-api)，将其导入语句切换至 `vue` 即可。注意有些通过插件暴露的 API，例如 `createApp`，并没有被移植回 2.7。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +如我们之前所提到的，2.7 是 Vue 2.x 的最后一个次级版本。在此发布之后，Vue 2 将会进入长期技术支持 (LTS：long-term support) 状态，该状态从现在起计算会持续 18 个月，且不再提供新特性。
```suggestion
如我们之前所提到的，2.7 是 Vue 2.x 的最后一个小版本。在此发布之后，Vue 2 将会进入长期技术支持 (LTS) 状态，该状态从现在起计算会持续 18 个月，且不再提供新特性。
```
前文提过了，可以省略。

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +# Vue 2 的长期技术支持 (LTS)、生命周期截止日 (EOL) 及其延长版服务
```suggestion
# Vue 2 的长期技术支持 (LTS)、终止支持 (EOL) 及其延长版服务
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +**Vue 2 的生命周期截止日将会是 2023 年 12 月 31 日**。在此之后，Vue 2 在已有的分发渠道 (各类 CDN 和包管理器) 中仍然可用，但不再进行更新，包括对安全问题和浏览器兼容性问题的修复等。
```suggestion
**Vue 2 的终止支持将会是 2023 年 12 月 31 日**。在此之后，Vue 2 在已有的分发渠道 (各类 CDN 和包管理器) 中仍然可用，但不再进行更新，包括对安全问题和浏览器兼容性问题的修复等。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +## 应对生命周期截止日的几个选项
```suggestion
## 应对终止支持的几个选项
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +有些团队可能鉴于有限的投入、预算、风险承受能力、或不兼容 Vue 3 的依赖，不会升级到 Vue 3。我们完全可以理解这种做法，并将确保留在 Vue 2 是完全可行的选项，即便在其生命周期截止之后。
```suggestion
有些团队可能鉴于有限的投入、预算、风险承受能力、或不兼容 Vue 3 的依赖，不会升级到 Vue 3。我们完全可以理解这种做法，并将确保留在 Vue 2 是完全可行的选项，即便在其终止支持之后。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +Vue 2.7 也是在生命周期截止日之前保持维护的版本，所以如果你打算留在 Vue 2，应该至少升级至 2.7。
```suggestion
Vue 2.7 也是在终止支持之前保持维护的版本，所以如果你打算留在 Vue 2，应该至少升级至 2.7。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +- 软件的生命周期截止之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个版本来应对合规或公司政策问题。
```suggestion
- 软件的终止支持之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个版本来应对合规或公司政策问题。
```

2023-01-29 12:39 UTC, veaba commented on src/lts/index.md
> +为了解决以上顾虑，我们和业内的专家们合作推出了 **Vue 2 的延长版 LTS 服务**。该服务会提供 Vue 2 安全和浏览器兼容性相关问题的修复版本，且带有 SLA 协议。如果你希望在 Vue 2 的生命周期截止日，即 2023 年 12 月 31 日之后，仍然使用它，一定要移步至：[学习更多关于 HeroDevs 对 Vue 2 的无限期支持](https://www.herodevs.
```suggestion
为了解决以上顾虑，我们和业内的专家们合作推出了 **Vue 2 的延长版 LTS 服务**。该服务会提供 Vue 2 安全和浏览器兼容性相关问题的修复版本，且带有 SLA 协议。如果你希望在 Vue 2 的终止支持，即 2023 年 12 月 31 日之后，仍然使用它，一定要移步至：[学习更多关于 HeroDevs 对 Vue 2 的无限期支持](https://www.herodevs.com/support/vue)。
```

2023-01-29 12:39 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +这意味着 **Vue 2 的生命周期截止日将会是 2023 年 12 月 31 日**。我们相信这将为生态系统的绝大部分提供充足的时间迁移至 Vue 3。然而，我们也理解有些团队或项目可能无法在这个时间段内升级，同时还要满足安全和合规等要求。如果你的团队希望在 2023 年底之后继续使用Vue 2，请确保提前做好计划并了解你的可选项：了解更多关于 [Vue 2 LTS 及其延长版服务](/lts
```suggestion
这意味着 **Vue 2 的终止支持将会是 2023 年 12 月 31 日**。我们相信这将为生态系统的绝大部分提供充足的时间迁移至 Vue 3。然而，我们也理解有些团队或项目可能无法在这个时间段内升级，同时还要满足安全和合规等要求。如果你的团队希望在 2023 年底之后继续使用Vue 2，请确保提前做好计划并了解你的可选项：了解更多关于 [Vue 2 LTS 及其延长版服务](/lts/)。
```

2023-01-29 12:45 UTC, veaba commented on src/v2/guide/migration-vue-2-7.md
> +## 带回的特性
```suggestion
## 移植回来的特性
```

2023-01-30 01:55 UTC, Jinjiang commented on src/lts/index.md
> +- 软件的生命周期截止之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个版本来应对合规或公司政策问题。
```suggestion
- 软件在终止支持之后通常不会修复新的安全问题。Vue 2 在过去尚未有过真正的安全问题的记录，但是你可能会需要一个版本来应对合规或公司政策问题。
```

2023-01-30 01:55 UTC, Jinjiang commented on src/lts/index.md
> +- 如果你在向客户提供带有 SLA (Service Level Agreement) 协议的应用，你*需要*在技术栈中避免包含生命周期截止日的软件。
```suggestion
- 如果你在向客户提供带有服务级别协议 (SLA：Service Level Agreement) 的应用，你*需要*在技术栈中避免包含生命周期截止日的软件。
```

2023-01-30 01:55 UTC, Jinjiang commented on src/v2/guide/migration-vue-2-7.md
> +Vue 2.7 是 Vue 2 最新的次级版本。其提供了内置的[组合式 API](https://cn.vuejs.org/guide/extras/composition-api-faq.html#composition-api-faq) 支持。
这里统一到次级版本了，之前的小版本我改掉了

2023-01-30 01:55 UTC, Jinjiang commented on src/v2/guide/migration-vue-2-7.md
> +- 当从外部构建 CJS 版本时，打包工具应该有能力在内部对 ESM 进行转换 (ESM interop)。
跟我的理解一致

2023-01-30 01:55 UTC, Jinjiang commented on src/v2/guide/migration-vue-2-7.md
> +这意味着 **Vue 2 的生命周期截止日将会是 2023 年 12 月 31 日**。我们相信这将为生态系统的绝大部分提供充足的时间迁移至 Vue 3。然而，我们也理解有些团队或项目可能无法在这个时间段内升级，同时还要满足安全和合规等要求。如果你的团队希望在 2023 年底之后继续使用Vue 2，请确保提前做好计划并了解你的可选项：了解更多关于 [Vue 2 LTS 及其延长版服务](/lts
```suggestion
这意味着 **Vue 2 的终止支持期限将会是 2023 年 12 月 31 日**。我们相信这将为生态系统的绝大部分提供充足的时间迁移至 Vue 3。然而，我们也理解有些团队或项目可能无法在这个时间段内升级，同时还要满足安全和合规等要求。如果你的团队希望在 2023 年底之后继续使用Vue 2，请确保提前做好计划并了解你的可选项：了解更多关于 [Vue 2 LTS 及其延长版服务](/lts/)。
```

2023-01-30 02:10 UTC, Jinjiang commented on src/v2/guide/migration-vue-2-7.md
> +Vue Devtools 6.2.0 已经支持了 2.7 组合式 API 状态的审查，但该扩展可能仍然需要几天时间在各自的发布平台上通过审核。
等英文版再更新吧，我就先这样翻译了 (事实上还有一部分内容已经又更新了，我打算等这个 PR merge 之后再翻译一波)

2023-01-30 02:10 UTC, Jinjiang commented on src/v2/guide/migration-vue-2-7.md
> +如我们之前所提到的，2.7 是 Vue 2.x 的最后一个次级版本。在此发布之后，Vue 2 将会进入长期技术支持 (LTS：long-term support) 状态，该状态从现在起计算会持续 18 个月，且不再提供新特性。
这篇文章之前没有提到过，提到过 LTS 的是 lts 那一页，所以这里我保留了

2023-01-30 02:21 UTC, veaba approved these changes

2023-01-30 02:22 UTC, veaba commented
我这边没问题了。 @Jinjiang @Justineo

2023-01-30 02:31 UTC, Justineo approved these changes

2023-01-30 02:34 UTC, merged